using Discord.Interactions;

namespace RyuBot.Commands.Interactions.Modules;

public partial class VerifierModule
{
    [SlashCommand("verify", "Verifies your modded Switch ownership via the Switch Verifier Homebrew.")]
    public async Task<RuntimeResult> VerifyAsync(
        [Summary(description: "The token generated by the Switch Verifier homebrew, after being given your hash.")] 
        string token)
    {
        await DeferAsync(true);

        var result = await Verifier.VerifyAsync(Context.User.Id, token);

        if (result is ResultCode.Success)
            await ((SocketGuildUser)Context.User).AddRoleAsync(1334992661198930001);

        return result switch
        {
            ResultCode.Success => Ok("Success! You can now get help."),
            ResultCode.InvalidInput => BadRequest("An input value was invalid."),
            ResultCode.InvalidTokenLength => BadRequest("The provided token didn't match the expected length."),
            ResultCode.TokenIsZeroes => BadRequest("Token is all zeroes."),
            ResultCode.ExpiredToken => BadRequest("The provided token has expired."),
            _ => BadRequest("Invalid token.")
        };
    }
}